name: "Code Analysis Terraform"

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - feat/**
      - fix/**

jobs:
  Code-Analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2

      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.11" # Forțează o versiune stabilă de Python pentru Checkov

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4.0.0
        with:
          terraform-version: "1.14.0"

      - name: Set up Terragrunt
        uses: autero1/action-terragrunt@v3.0.2
        with:
          terragrunt-version: "0.99.4"

      # Pas critic: Creează folderul de output pentru a evita erorile de scriere
      - name: Create Output Directory for Reports
        run: mkdir -p .github/output

      # Rulează toate hook-urile (inclusiv Checkov care va scrie în folderul creat mai sus)
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

      # Încarcă rezultatele în Security Tab-ul din GitHub (rulează chiar dacă scanarea a găsit vulnerabilități)
      - name: Upload Checkov SARIF file
        uses: github/codeql-action/upload-sarif@v4
        if: always() # Folosim "always()" pentru a ne asigura că primim raportul și când pre-commit-ul pică!
        with:
          sarif_file: .github/output/results.sarif
